services:
  file-storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: file-storage-service:0.0.1
    container_name: file-storage
    ports:
      - "3001:3001"
    volumes:
      - ./storage:/app/storage
    environment:
      - PORT=3001
      - NODE_ENV=production
      - STORAGE_PATH=/app/storage
      - MAX_FILE_SIZE=52428800
    restart: unless-stopped
